#!/usr/bin/env bash

# this script is used for judging a solution
# and generating output locally
#

declare -r __script_name='setter'
declare -r __script_version='0.3.0'

exec_file="$(readlink -f "$0")"
commands_path="$(dirname "$exec_file")"
export _SETTER_DIR="$(dirname "$commands_path")"
export PATH="$PATH:${commands_path}"

source "${_SETTER_DIR}/utils/util.sh"

usage() {
  cat << EOF
Usage: ${__script_name} [options...] <command>

Options:
  -h, --help            Show this help message
  -V, --version         Show script version

Available commands:
  judge                 Judge your solution
  gen                   Generate output from input files
  validate		Validate input files with your validator
EOF
}

version() {
  printf "%s v%s\n" "${__script_name}" "${__script_version}"
}

subcommand="$1"
case "$subcommand" in 
  "" | -h | --help)
    usage; exit 0 ;;
  -V | --version)
    version; exit 0 ;;
  -*)
    ecerr "invalid option '%s'" "$subcommand"
    show_try_help
    exit 2 ;;
  *)
    command_path="$(command -v "${__script_name}_${subcommand}")"
    if [[ ! -x "$command_path" ]]; then
      ecerr "unknown command '%s'" "$subcommand"
      show_try_help
      exit 127
    fi
    shift
    exec "$command_path" "$@"
esac
