#!/usr/bin/env bash

# generating output files from provided input files
#
# requires:
#   time (not a shell keyword one)
#

declare -r __script_name='setter gen'

if [[ -f "${_SETTER_DIR}/env/colors.sh" ]]; then
  source "${_SETTER_DIR}/env/colors.sh"
fi
source "${_SETTER_DIR}/utils/util.sh"

input_dir="in"
output_dir="out"
checker="checker.out"
time_command="$(which time 2> /dev/null)" # do not use time shell keyword

if [[ -z "$time_command" ]]; then
  missing_cmd "time"
fi

if ! cmd_exists "timeout"; then
  missing_cmd "timeout"
fi

function usage() {
  cat << EOF
Usage: ${__script_name} [options...]

Options:
  -c, --checker <file>      Checker file to run (default: ${checker})
  -i, --input-dir <dir>     Directory that contains input files (default: ${input_dir})
  -o, --output-dir <dir>    Directory to place output files (default: ${output_dir})
  -h, --help                Show this help message
EOF
}

options='c:i:o:h'
long_options='checker:,input:,output:,help'

OPTS=$(getopt --name "$__script_name" --options "$options" \
      --longoptions "$long_options" -- "$@")

if (( $? != 0 )); then
  show_try_help
  exit 2
fi
eval set -- "$OPTS"

while true; do
  case "$1" in
    -h | --help)
      usage; exit 0 ;;
    -c | --checker)
      checker="$2"; shift 2 ;;
    -i | --input-dir)
      input_dir="$2"; shift 2 ;;
    -o | --output-dir)
      output_dir="$2"; shift 2 ;;
    --)
      shift; break ;;
    *)
      echo "Unknown option: $1" >&2; shift ;;
  esac
done

if [[ ! -f "$checker" ]]; then
  ecerr "could not find checker file: %s" "$checker"
  exit 2
fi

if [[ ! -d "$input_dir" ]]; then
  ecerr "could not find input directory: %s" "$input_dir"
  exit 2
fi

if [[ -d "$output_dir" ]]; then
  printf "Directory '%s' already exists. Overwrite? [Y/n] " "$output_dir"
  read -r answer
  case "$answer" in 
    y | Y)
      rm -rf "$output_dir" ;;
    *)
      exit 0 ;;
  esac
fi

mkdir -p "$output_dir"

if [[ "$(basename "$checker")" == "$checker" ]]; then
  checker="./${checker}"
fi

input_num=$(find "$input_dir" -iname "*.in" | wc -l)

if (( input_num == 0 )); then
  ecerr "no input file found in '%s'" "$input_dir"
  exit 2
fi

declare -i input_cnt=1
exec_info_file="$(mktemp)"
exec_info_format=$(cat << EOF
elapsed time:%e
memory:%M
EOF
)

trap 'rm -f "${exec_info_file}"' EXIT

exit_code=0
for input in "${input_dir}"/*.in; do
  input_basename=$(basename "$input" .in)
  output="${output_dir}/${input_basename}.out"
  echo -en " (${LIGHT_GREEN}${input_cnt}${RESET}/${MAGENTA}${input_num}${RESET}) ${input}"
  "$time_command" -f "$exec_info_format" -o "$exec_info_file" \
      "$checker" < "$input" > "$output" 2> /dev/null 

  if (( $? != 0 )); then
    echo -e "\t${B_RED}FAILED${RESET}"
    rm -f "$output"
    exit_code=1
  else
    elapsed_time=$(cat "$exec_info_file" | grep 'elapsed time' | awk -F: '{print $2}')
    memory=$(cat "$exec_info_file" | grep 'memory' | awk -F: '{print $2}')
    memory=$(( memory / 1024 ))
    echo -e "${LIGHT_BLUE}\t-->${RESET} ${output}\t${B_GREEN}OK${RESET} (${elapsed_time}s, ${memory} MB)"
  fi
  input_cnt+=1
done

exit $exit_code
