#!/usr/bin/env bash

# generating output files from provided input files
#
# requires:
#   time (not a shell keyword one, can be installed with `sudo apt install -y time`)
#

declare -r __script_name='setter gen'

source "${_SETTER_DIR}/env/colors.sh"
source "${_SETTER_DIR}/utils/util.sh"
source "${_SETTER_DIR}/utils/comp.sh"

input_dir="in"
output_dir="out"
time_command="$(which time 2> /dev/null)" # do not use time shell keyword

if [[ -z "$time_command" ]]; then
  missing_cmd "time"
fi

if ! cmd_exists "timeout"; then
  missing_cmd "timeout"
fi

usage() {
  cat << EOF
Usage: ${__script_name} [options...] <checker>

Options:
  -i, --input-dir <dir>     Directory that contains input files (default: ${input_dir})
  -o, --output-dir <dir>    Directory to place output files (default: ${output_dir})
  -h, --help                Show this help message
EOF
}

options='i:o:h'
long_options='input:,output:,help'

OPTS=$(getopt --name "$__script_name" --options "$options" \
       --longoptions "$long_options" -- "$@")

if (( $? != 0 )); then
  show_try_help
  exit 2
fi
eval set -- "$OPTS"

while true; do
  case "$1" in
    -i | --input-dir)
      input_dir="$2"; shift 2 ;;
    -o | --output-dir)
      output_dir="$2"; shift 2 ;;
    -h | --help)
      usage; exit 0 ;;
    --)
      shift; break ;;
    *)
      ecerr "unknown option: $1"; shift ;;
  esac
done

if (( $# < 1 )); then
  usage
  exit 1
fi

checker="$1"
ext_file="${checker##*.}"
if [[ "$ext_file" == "$checker" ]]; then
  # the file has no extension, so assume it's .cpp file
  ext_file="cpp"
  checker="${checker}.cpp"
fi

case "$ext_file" in
  out)
    if [[ ! -x "$checker" ]]; then
      ecerr "'%s' is not executable" "$checker"
      exit 1
    fi
    ;;
  cpp | c\+\+)
    exec_file="$(comp "$checker")"
    if [[ -z "$exec_file" ]]; then
      ecerr "failed to compile '%s'" "$checker"
      exit 1
    fi
    checker="$exec_file"
    ;;
  *)
    ecerr "checker must be a executable or cpp file"
    exit 1
    ;;
esac

if [[ "$(basename "$checker")" == "$checker" ]]; then
  checker="./${checker}"
fi

if [[ ! -d "$input_dir" ]]; then
  ecerr "could not find input directory: %s" "$input_dir"
  exit 2
fi

if [[ -d "$output_dir" ]]; then
  printf "Directory '%s' already exists. Overwrite? [Y/n] " "$output_dir"
  read -r answer
  case "$answer" in 
    y | Y)
      rm -rf "$output_dir" ;;
    *)
      exit 0 ;;
  esac
fi

mkdir -p "$output_dir"

num_inp_files=$(find "$input_dir" -iname "*.in" | wc -l)

if (( num_inp_files == 0 )); then
  ecerr "no input file found in '%s'" "$input_dir"
  exit 2
fi

input_cnt=1
resources_format="%e;%M"
resources_file="$(mktemp)"

trap 'rm "$resources_file"' EXIT

exit_code=0
for input in "${input_dir}"/*.in; do
  input_basename=$(basename "$input" .in)
  output="${output_dir}/${input_basename}.out"
  echo -en " (${LIGHT_GREEN}${input_cnt}${RESET}/${MAGENTA}${num_inp_files}${RESET}) ${input}"
  $time_command -f "$resources_format" -o "$resources_file" \
      "$checker" < "$input" > "$output" 2> /dev/null

  running_exit_code=$?
  if (( running_exit_code != 0 )); then
    echo -e "\t${B_RED}FAILED${RESET}"
    rm -f "$output"
    exit_code=1
  else
    elapsed_time="$(awk -F';' '{print $1}' "$resources_file")"
    memory_usage="$(awk -F';' '{print $2}' "$resources_file")"
    (( memory_usage *= 1000 ))
    memory_usage="$(echo "$memory_usage" | numfmt --to=si --format="%0.1f" --suffix=B)"
    echo -e "${LIGHT_BLUE}\t-->${RESET} ${output}\t${B_GREEN}OK${RESET} (${elapsed_time}s, ${memory_usage})"
  fi
  (( input_cnt += 1 ))
done

exit $exit_code
