#!/usr/bin/env bash

# judging a solution locally
#
# requires:
#   time (not a built-in keyword one)
#   timeout
#

declare -r __script_name='setter judge'

if [ -f "${_SETTER_DIR}/env/colors.sh" ]; then
  . "${_SETTER_DIR}/env/colors.sh"
fi
source "${_SETTER_DIR}/utils/util.sh"

src_file="sol.out"
input_dir="in"
output_dir="out"
time_limit="1s"
memory_limit="256MB"
time_command="$(which time 2> /dev/null)" # do not use time shell keyword

if [[ -z "$time_command" ]]; then
  missing_cmd "time"
fi

if ! cmd_exists "timeout"; then
  missing_cmd "timeout"
fi

function usage() {
  cat << EOF
Usage: ${__script_name} [options...]

Options:
  -s, --source <file>       Source file to check (default: ${src_file})
  -i, --input-dir <dir>     Directory that contains input files (default: ${input_dir})
  -o, --output-dir <dir>    Directory that contains output files (default: ${output_dir})
  -t, --time <second>       Set time limit (default: ${time_limit})
  -m, --memory <memory>     Set memory limit (default: ${memory_limit})
  -h, --help                Show this help message
EOF
}

options='hs:i:o:t:m:'
long_options='help,source:,input:,output:,time:,memory:'

OPTS=$(getopt --name "$__script_name" --options "$options" \
      --longoptions "$long_options" -- "$@")

if (( $? != 0 )); then
  show_try_help
  exit 2
fi
eval set -- "$OPTS"

while true; do
  case "$1" in
    -h | --help)
      usage; exit 0;;
    -s | --source)
      src_file="$2"; shift 2 ;;
    -i | --input-dir)
      input_dir="$2"; shift 2 ;;
    -o | --output-dir)
      output_dir="$2"; shift 2 ;;
    -t | --time)
      time_limit="${2%s}s"; shift 2 ;;
    -m | --memory)
      memory_limit="$2"; shift 2 ;;
    --)
      shift; break ;;
    *)
      echo "Unknown option: $1" >&2; shift ;;
  esac
done

if [[ ! -x "$src_file" ]]; then
  ecerr "'%s' is not executable file" "$src_file"
  exit 2
fi

if [[ ! -d "$input_dir" ]]; then
  ecerr "could not find input directory: %s" "$input_dir"
  exit 2
fi

if [[ ! -d "$output_dir" ]]; then
  ecerr "could not find output directory: %s" "$output_dir"
  exit 2
fi

if [[ "$(basename "$src_file")" == "$src_file" ]]; then
  src_file="./${src_file}"
fi

input_num=$(find "$input_dir" -iname "*.in" | wc -l)

if (( input_num == 0 )); then
  ecerr "no input file found in '%s'" "$input_dir"
  exit 2
fi

declare -i input_cnt=1 total_ac=0
output_temp_file="$(mktemp)"
exec_info_file="$(mktemp)"
exec_info_format=$(cat << EOF
elapsed time:%e
memory:%M
EOF
)
trap 'rm "$exec_info_file" "$output_temp_file"' EXIT

exit_code=0
total_exec_time=0
max_exec_time=
max_memory=

for input in "${input_dir}"/*.in; do
  input_basename=$(basename "$input" .in)
  ans="${output_dir}/${input_basename}.out"
  echo -en " (${LIGHT_GREEN}${input_cnt}${RESET}/${MAGENTA}${input_num}${RESET}) ${input}"
  if [[ ! -f "$ans" ]]; then
    echo -e "\t${GRAY}SKIP${RESET} (${B_BLUE}${ans}${RESET} not found)"
    exit_code=1
    continue
  fi

  timeout "$time_limit" "$time_command" -f "$exec_info_format" -o "$exec_info_file" \
      "$src_file" < "$input" > "$output_temp_file"
  exec_exit_code=$?
  if (( exec_exit_code != 0 )); then
    if (( exec_exit_code == 124 )); then 
      # command times out 
      echo -e "\t${B_RED}TLE${RESET} (> $time_limit)"
    else
      # assume exit code is returned by `src_file`
      echo -e "\t${B_RED}RUN TIME${RESET} (exit_code=$exec_exit_code)"
    fi
    exit_code=1
  elif ! diff -Zb "$output_temp_file" "$ans" &> /dev/null; then
    # wrong answer
    echo -e "\t${B_RED}WA${RESET}"
    exit_code=1
  else
    elapsed_time=$(cat "$exec_info_file" | grep 'elapsed time' | awk -F: '{print $2}')
    memory=$(cat "$exec_info_file" | grep 'memory' | awk -F: '{print $2}')

    if [[ -z "$max_exec_time" ]] || (( $(echo "$max_exec_time < $elapsed_time" | bc -l) )); then
      max_exec_time="$elapsed_time"
    fi
    if [[ -z "$max_memory" ]] || (( $(echo "$max_memory < $memory" | bc -l) )); then
      max_memory="$memory"
    fi
    memory=$(( memory / 1024 ))
    total_exec_time=$( echo "$total_exec_time + $elapsed_time" | bc -l )
    echo -e "\t${B_GREEN}OK${RESET} (${elapsed_time}s, ${memory} MB)"
    total_ac+=1
  fi
  input_cnt+=1
done

echo "Total AC     : ${total_ac}/${input_num}"
echo "Finished in  : ${total_exec_time}s"
echo "Max run time : ${max_exec_time}s"
echo "Max memory   : $(( max_memory / 1024)) MB"
exit $exit_code
